### ISSUE TITLE
Catch up with bug-fix relevant PRs on node-irc

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/node-irc#19]
The following are relevant to us:
 - https://github.com/martynsmith/node-irc/pull/487
 - https://github.com/martynsmith/node-irc/pull/396
 - https://github.com/martynsmith/node-irc/pull/397
 - https://github.com/martynsmith/node-irc/pull/443

**Comment by Kegsay** [comment]
https://github.com/martynsmith/node-irc/issues/507 possibly.

**Comment by intelfx** [comment]
Should probably be closed as #22 is merged.

**Comment by chrisdotcode** [comment]
@Kegsay  We haven't merged martynsmith#507 as of yet.

**Comment by intelfx** [comment]
@chrisdotcode Isn't it an issue (as opposed to a PR)?
