### ISSUE TITLE
IRC formatting codes break UTF-8 auto detection and force encodingFallback use

### ISSUE THREAD

**Issue by ilmari** [matrix-org/node-irc#44]
On the IRCnet bridge, actions appear to always be interpreted as the fallback encoding (ISO-8859-15)

On the IRC side (client configured to send UTF-8)
```
<@ilmari> æøå
* ilmari æøå
[notice(#chan)] æøå
```

On the Matrix side:
```
ilmari (@_ircnet_ilmari:irc.snt.utwente.nl)
æøå
* ilmari (@_ircnet_ilmari:irc.snt.utwente.nl) ÃŠÃžÃ¥
æøå
```
![Screenshot from 2020-05-18 12-14-43](https://user-images.githubusercontent.com/72175/82207139-429fb000-9901-11ea-9674-ed693cd471eb.png)

While my notice was correctly decoded as UTF-8 here, on another channel a bot's UTF-8 notices are decoded as ISO-8859-15:

IRC:
```
-lorelai- [1] spot boston dynamics horse mask (0:13) by Мария Прокопенко [+24/-0, 1519 views]
```

Matrix:
```
[1] spot boston dynamics horse mask (0:13) by ÐÐ°ÑÐžÑ ÐÑÐŸÐºÐŸÐ¿ÐµÐœÐºÐŸ [+24/-0, 1519 views]
```
![Screenshot from 2020-05-18 12-18-47](https://user-images.githubusercontent.com/72175/82207464-c78ac980-9901-11ea-994b-67e4063a0a1a.png)

**Comment by ilmari** [comment]
On another channel where my client is configured to send ISO-8859-15, it works correctly:

IRC:
```
< ilmari> skjærgårdsøl?
* ilmari liker skjærgårdsøl
[notice(#otherchan)] skjærgårdsøl!
```

Matrix:
```
ilmari (@_ircnet_ilmari:irc.snt.utwente.nl)
skjærgårdsøl?
* ilmari (@_ircnet_ilmari:irc.snt.utwente.nl) liker skjærgårdsøl
skjærgårdsøl!
```
![Screenshot from 2020-05-18 12-23-24](https://user-images.githubusercontent.com/72175/82207848-66afc100-9902-11ea-882d-5d82b0681ad9.png)

**Comment by ilmari** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/580#issuecomment-638111256 made me realise that the notices that get mangled have text formatting codes in them:

```json
{
  "content": {
    "body": "[1] Dagfinn Ilmari MannsÃ¥ker",
    "format": "org.matrix.custom.html",
    "formatted_body": "<b>[1]</b> Dagfinn Ilmari MannsÃ¥ker",
    "msgtype": "m.notice"
  },
  "event_id": "$1591183492575491NNmPv:irc.snt.utwente.nl",
  "origin_server_ts": 1591183492274,
  "sender": "@_ircnet_lorelai:irc.snt.utwente.nl",
  "type": "m.room.message",
  "unsigned": {
    "age": 3376
  },
  "room_id": "!WNiVmWxmsBkMsusLnT:irc.snt.utwente.nl"
}
```

**Comment by ilmari** [comment]
Explanation by @leonerd:
> PRIVMSG contents can swap between regular text and "CTCP", client-to-client protocol, with a single `\x01` byte
> An action is the CTCP ACTION command, so in full it looks like `:Sender!ident@prefix.here PRIVMSG  #target :\x01ACTION the action here`
> it probably doesn't strip CTCPs apart properly
> on IRC you have to strip out CTCP -before- you apply Unicode decoding

**Comment by zouppen** [comment]
Not only used in CTCP's but the payload itself may contain codes as well in case of colours and text formatting. So, proper implementation should parse the message codes first and then recode.

**Comment by vranki** [comment]
Yep, this becomes a bit complex as the CTCP messages need quite lot more tuning.

Perhaps we could just disable fallback encoding on any CTCP strings - this way at least UTF-8 actions would work as expected.

**Comment by ilmari** [comment]
> Perhaps we could just disable fallback encoding on any CTCP strings - this way at least UTF-8 actions would work as expected.

That still doesn't solve it for messages with colour/formatting codes.

**Comment by ilmari** [comment]
This turns out to be because `is-utf8` [mistakenly classifies](https://github.com/wayfind/is-utf8/issues/6) strings with C0 control characters (except TAB, CR and LF) as non-UTF-8.

An alternative mentioned in the above ticket is [`utf-8-validate`](https://github.com/websockets/utf-8-validate).

**Comment by vranki** [comment]
Good find, thanks.

**Comment by vranki** [comment]
PR #49 made.

**Comment by Half-Shot** [comment]
Believe this is fixed now.
