### ISSUE TITLE
`CAP REQ SASL` expects a space?

### ISSUE THREAD

**Issue by slingamn** [matrix-org/node-irc#45]
I got a bug report that matrix-appservice-irc wasn't correctly connecting to [oragono](https://github.com/oragono/oragono) with SASL. I think the culprit is this line:

https://github.com/matrix-org/node-irc/blob/7feccae6c168c2c08527daace0c6fe5af56c6560/lib/irc.js#L663

I'm not sure where the expectation came from that there would be a space after 'sasl', but I'm pretty confident that it's incorrect to require this.

Thoughts? Thanks for your time.

**Comment by Half-Shot** [comment]
Fixed in #47
